ballerina/build.gradle

Bring latest changes to temporary branch

---

native/build.gradle

Update publish script to use persist.sql native

---

gradle.properties

Update persist version

---

ballerina/sql_client.bal

Remove entity names from being included in the update and delete SQL queries

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
ballerina/build.gradle
build-config/resources/Ballerina.toml
gradle.properties

Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/4568
N/A

Mark GraalVM compatibility

---

gradle.properties

Update dependency versions for U7

---

.github/workflows/build-timestamped-master.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/publish-snapshot-nexus.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml
README.md
ballerina/Ballerina.toml
ballerina/build.gradle
build-config/checkstyle/build.gradle
build-config/resources/Ballerina.toml
gradle.properties
gradle/wrapper/gradle-wrapper.properties
native/build.gradle
settings.gradle

Migrate to Java 17

---

gradle.properties

Bump latest dependencies

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Bump minor version and update distribution 

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/sql/compiler/DiagnosticsCodes.java

Update diagnostics'  messages

---

.github/workflows/publish-release.yml
native/build.gradle

$Subject
Fixes:[5769](https://github.com/ballerina-platform/ballerina-library/issues/5768)

Update publish-release.yml to include nexus credentials as env variables

---

.github/workflows/build-timestamped-master.yml
.github/workflows/publish-release.yml
native/build.gradle

Fixes:[5768](https://github.com/ballerina-platform/ballerina-library/issues/5768)

Revert changes to `publish-release` and `build-timestamped-master` workflows

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
gradle.properties

Update persist timestamped version

---

ballerina/Dependencies.toml
ballerina/constants.bal
ballerina/metadata_types.bal
ballerina/sql_client.bal
ballerina/tests/init-tests.bal
ballerina/tests/postgresql-composite-key-tests.bal
ballerina/tests/postgresql-employee-tests.bal
ballerina/tests/postgresql-native-tests.bal
ballerina/tests/postgresql-workspace-tests.bal
ballerina/tests/resources/postgresql/init.sql

Escape all table and column names

---

.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/central-publish.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml

Update standard lib reusable worklfow links

---

ballerina/build.gradle

This is to fix the build failure due to the recent change in the mssql-docker image.
Refer: https://github.com/microsoft/mssql-docker/issues/892

Update health check path in mssql docker

---

.github/workflows/build-timestamped-master.yml
.github/workflows/publish-release.yml
.github/workflows/publish-snapshot-nexus.yml

Update the github workflows versions

---

.github/workflows/publish-release.yml
.github/workflows/trivy-scan.yml
ballerina/Dependencies.toml

Add env to fix the TOOMANYREQUESTS issues

---

.github/workflows/publish-release.yml
.github/workflows/trivy-scan.yml

Fix the error: no such file or directory

---

.github/workflows/publish-release.yml

Move the trivy plugin to the latest with scan-ref change

---

.github/workflows/publish-release.yml

[Trivy action] Set scanner to scan only vulnerabilities

---

.github/workflows/build-timestamped-master.yml
.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/publish-snapshot-nexus.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml
README.md
ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
compiler-plugin-test/build.gradle
compiler-plugin/build.gradle
gradle.properties
native/build.gradle
native/src/main/java/io/ballerina/stdlib/persist/sql/Handler.java
native/src/main/java/io/ballerina/stdlib/persist/sql/ModuleUtils.java
native/src/main/java/io/ballerina/stdlib/persist/sql/datastore/SQLProcessor.java

Migrate to Java 21

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
gradle.properties

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7381
N/A

Fix GraalVM test failure after mssql driver version update

---

.github/workflows/publish-release.yml
ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
build.gradle
compiler-plugin-test/build.gradle
compiler-plugin/build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
native/build.gradle
settings.gradle

Update version for the update 11

---

build.gradle
gradle.properties

Update dependencies for the update11
